FROM python:3.6

WORKDIR /usr/share/fn-dash

RUN apt-get update && \
    apt-get install netcat -y

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP manage.py
ENV FLASK_ENV development

CMD ["python", "manage.py", "runserver"]