"""Add hash

Revision ID: 13beba38f2af
Revises: d9e46a91ea19
Create Date: 2019-05-04 19:07:49.146594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13beba38f2af'
down_revision = 'd9e46a91ea19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_known_data_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_known_data_hash')
    # ### end Alembic commands ###
