"""empty message

Revision ID: 4c05385e6a2f
Revises: cf2f8cad42fa
Create Date: 2019-03-03 21:39:58.775793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c05385e6a2f'
down_revision = 'cf2f8cad42fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_mode_uc', 'stat', type_='unique')
    op.create_unique_constraint('_name_mode_uc', 'stat', ['user_id', 'name', 'mode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_mode_uc', 'stat', type_='unique')
    op.create_unique_constraint('_name_mode_uc', 'stat', ['name', 'mode'])
    # ### end Alembic commands ###
