"""empty message

Revision ID: be30518dd2c5
Revises: b9d428b1eaa5
Create Date: 2019-01-20 22:29:37.433863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be30518dd2c5'
down_revision = 'b9d428b1eaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('placetop12_duo', sa.Integer(), nullable=True))
    op.drop_column('user', 'placetop10_duo')
    op.drop_column('user', 'placetop25_duo')
    op.add_column('user', sa.Column('placetop5_duo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('placetop10_duo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'placetop12_duo')
    op.add_column('user', sa.Column('placetop25_duo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'placetop5_duo')
    # ### end Alembic commands ###

