"""empty message

Revision ID: cf2f8cad42fa
Revises: 3553d253c34b
Create Date: 2019-03-03 21:02:46.516203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf2f8cad42fa'
down_revision = '3553d253c34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('is_ltm', sa.Boolean(), nullable=False),
    sa.Column('placements', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('matchesplayed', sa.Integer(), nullable=True),
    sa.Column('playersoutlived', sa.Integer(), nullable=True),
    sa.Column('minutesplayed', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'mode', name='_name_mode_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat')
    # ### end Alembic commands ###
