"""empty message

Revision ID: d80927e6e3b0
Revises: e8c0bca962a9
Create Date: 2019-03-03 21:54:22.138074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd80927e6e3b0'
down_revision = 'e8c0bca962a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('placements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat', 'placements')
    # ### end Alembic commands ###
