"""Drop hash

Revision ID: d9e46a91ea19
Revises: 707731268b3e
Create Date: 2019-05-04 19:07:22.057597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e46a91ea19'
down_revision = '707731268b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_known_data_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_known_data_hash', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
