"""empty message

Revision ID: dba68d37092b
Revises: a289d98ff88a
Create Date: 2019-05-04 13:58:07.024430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba68d37092b'
down_revision = 'a289d98ff88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat', sa.Column('input_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('_input_name_mode_uc', 'stat', ['input_id', 'name', 'mode'])
    op.create_foreign_key(None, 'stat', 'input', ['input_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stat', type_='foreignkey')
    op.drop_constraint('_input_name_mode_uc', 'stat', type_='unique')
    op.drop_column('stat', 'input_id')
    # ### end Alembic commands ###
