"""empty message

Revision ID: eafc1b0e40ec
Revises: d80927e6e3b0
Create Date: 2019-03-08 23:56:08.402348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafc1b0e40ec'
down_revision = 'd80927e6e3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('_name_mode_ix', 'stat', ['name', 'mode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_name_mode_ix', table_name='stat')
    # ### end Alembic commands ###
